name: scientific_python
channels:
  - defaults
dependencies:
  - bokeh
  - ipywidgets
  - jupyter
  - matplotlib
  - nodejs
  - numexpr
  - numpy
  - opencv
  - pandas
  - pytables
  - python=3.7.5
  - scikit-image
  - scipy
  - sympy
  - xlrd=1.2.0=py37_0
